apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment  # Should be lowercase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld-container  # Should be lowercase
          image: 891612555773.dkr.ecr.ap-south-1.amazonaws.com/javajankinsrepo:latest
          ports:
            - containerPort: 8081


